# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: graphql-java-annotations

on:
  push:
    paths:
      - "graphql-java-annotations/**"
    branches: [ master ]
  pull_request:
    paths:
      - "graphql-java-annotations/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Setup Postgres in Docker 
      run: |
        docker-compose up -d postgres
        docker ps -a
    - name: Build with Gradle
      run: |
        cd graphql-java-annotations
        chmod +x gradlew
        ./gradlew build

 