# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: spring-graphql-querydsl

on:
  push:
    paths:
      - "spring-graphql-querydsl/**"
    branches: [ master ]
  pull_request:
    paths:
      - "spring-graphql-querydsl/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Postgres in Docker 
      run: |
        docker-compose up -d postgres
        docker ps -a
    - name: Build with Gradle
      run: |
        cd spring-graphql-querydsl
        chmod +x gradlew
        ./gradlew build                        
           
